onlinesustredka/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quiz/', include('quiz.urls')),
]

quiz/urls.py
from quiz import views
from django.urls import include, path

app_name = 'quiz'

urlpatterns = [
    path('start', views.start, name='start'),
    path('create-game/<int:pk>/',views.create_game,name='create-game'),
    path('start-game/<int:pk>/', views.start_game, name='start-game'),
    path('game/<int:pk>/', views.game, name='game'),
    path('results', views.results, name='results'),
    path('player-not-found', views.question, name='player-not-found')

]

quiz/models.py
from django.db import models
from django.utils import timezone
import random
import unidecode

def unify(text):  
    text = text.strip()
    text = unidecode.unidecode(text)
    return text.lower().replace(',','.')

class QuestionTag(models.Model):
    class Meta:
        verbose_name = 'kategória'
        verbose_name_plural = 'kategórie'
    name = models.CharField(max_length=50)
    sample = models.PositiveSmallIntegerField()
    
    def __str__(self):
        return self.name

class SimpleQuestion(models.Model):
    text = models.TextField()
    answer = models.TextField()
    tag = models.ForeignKey(QuestionTag,null=True,on_delete=models.CASCADE,related_name='question_set')
    def __str__(self):
        return self.text


class Player(models.Model):
    class Meta:
        verbose_name = 'Účastník'
        verbose_name_plural = 'Účastníci'

    email = models.EmailField()
    nickname = models.CharField(max_length=50)

    def create_game(self):
        gr = GameRecord.objects.create(points=0,player=self,current_question_n=0)
        tags = QuestionTag.objects.all()
        questions=[]
        for tag in tags:
            questions+=random.sample(list(tag.question_set.all()),tag.sample)
        for i,q in enumerate(questions):
            QuestionInGame.objects.create(order=i,question=q,game=gr)
        gr.num_questions = len(questions)
        gr.save()
        return gr
    def __str__(self):
        return f'{self.nickname} ({self.email})'
        


class GameRecord(models.Model):
    class Meta:
        verbose_name = 'Záznam hry'
        verbose_name_plural = 'Záznamy hry'

    points = models.PositiveSmallIntegerField()
    time = models.FloatField(null=True)
    start_at = models.DateTimeField(default=None,null=True)
    player = models.ForeignKey(Player,on_delete=models.CASCADE)
    current_question_n = models.PositiveSmallIntegerField(null=True)
    num_questions = models.PositiveSmallIntegerField(null=True)
    def __str__(self):
        return f'{self.player} - {self.start_at}'

    def current_question(self):
        if self.current_question_n>=self.num_questions:
            return None
        return self.questions.filter(order=self.current_question_n).first().question

    def answer_and_get_next(self,answer):
        q = self.questions.filter(order=self.current_question_n).first()
        q.player_answer = unidecode.unidecode(str(answer)).lower()
        q.save()
        self.current_question_n=self.current_question_n+1
        self.save()
        if self.current_question_n>=self.num_questions:
            return None
        return self.current_question()

    def evaluate(self):
        self.time = (timezone.now()-self.start_at).seconds
        points=0
        for q in self.questions.all():
            points+= 1 if q.validate() else 0
        self.points = points
        self.save()
        return self.points,self.time
        

class QuestionInGame(models.Model):
    game = models.ForeignKey(GameRecord,on_delete=models.CASCADE,related_name='questions')
    question = models.ForeignKey(SimpleQuestion,on_delete=models.CASCADE)
    player_answer = models.CharField(max_length=50,verbose_name='Odpoveď',blank=True)
    order = models.PositiveSmallIntegerField()

    def validate(self):
        return unify(self.player_answer) == unify(self.question.answer)

quiz/forms.py
from django import forms

class StartForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=100)

quiz/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect, get_object_or_404
from django.utils import timezone
from django.urls import reverse
from django.views.generic import ListView

from quiz.forms import StartForm
from quiz import models

from functools import cmp_to_key

class ContactList(ListView):
    paginate_by = 2
    model = models.SimpleQuestion

def question(request):
    contact_list = models.SimpleQuestion.objects.all()
    paginator = Paginator(contact_list, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'quiz/list.html', {'page_obj': page_obj})

def create_game(request,pk):
    player = models.Player.objects.get(pk=pk)
    g = player.create_game()
    return redirect(reverse('quiz:start-game',args=[g.pk]))

def start(request):
    if request.method == 'POST':
        form = StartForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # Create quiz session object and start it
            try:
                player = models.Player.objects.get(email=form.cleaned_data['email'])
            except models.Player.DoesNotExist:
               return render(request, 'quiz/wrong_player.html', {'email': form.cleaned_data['email']})
            g = player.create_game()
            return redirect(reverse('quiz:start-game',args=[g.pk]))
    else:
        form = StartForm()

    return render(request, 'quiz/start.html', {'form': form})

def game(request,pk):
    gr = get_object_or_404(models.GameRecord,pk=pk)
    if request.method == 'POST':
        answer = request.POST['answer']
        q  = gr.answer_and_get_next(answer)
    else:
        q = gr.current_question()
    if q is None:
        if gr.time is None:
            gr.evaluate()
        return render(request,'quiz/game_results.html',{'player': gr.player,'game_time':gr.time,'points':gr.points,'max_points':gr.num_questions})
    return render(request,'quiz/question.html',{'question_tag':q.tag,'question_text':q.text,'pk':pk})
        


def start_game(request,pk):
    gr = get_object_or_404(models.GameRecord,pk=pk)
    if request.method == 'POST':
        
        if gr.start_at is not None:
            return redirect(reverse('quiz:game',args=[pk]))
        gr.start_at = timezone.now()
        gr.current_question_n = 0
        gr.save()
        return redirect(reverse('quiz:game',args=[pk]))
    else:
        return render(request, 'quiz/instructions.html', {'player': gr.player,'pk':pk})


def results(request):
    # Sort by player
    records = models.GameRecord.objects.filter(time__isnull=False).order_by('player','-points','time','start_at')
    
    # Get best for every player
    result_board = []
    current_player = None
    for rec in records:
        if rec.player!=current_player: 
            result_board.append(rec)
            current_player = rec.player

    # Sort
    def comp_rec(it1,it2):
        if it1.points>it2.points:
            return -1
        elif it1.points<it2.points:
            return 1
        else:
            if it1.time>it2.time:
                return 1
            elif it1.time<it2.time:
                return -1
            else:
                return 0
    result_board = sorted(result_board,key=cmp_to_key(comp_rec))

    # Render
    return render(request, 'quiz/results.html', {'results': result_board})

quiz/templates/quiz/base.html
<head>
{% load static %}
    {% block css %}
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css" integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />
      <link rel="stylesheet" type="text/css" href="{% static 'mystyle.css' %}">
    {% endblock css %}
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script>
      MathJax = {
        tex: {
          inlineMath: [['$', '$'], ['\\(', '\\)']]
        },
        svg: {
          fontCache: 'global'
        }
      };
      </script>
</head>
<body OnLoad="document.answer_form.answer.focus();">
  <div style='margin: 5% 10% 5% 10%;'>
    {% block content %} 
    {% endblock content %}
  </div>
</body>
{% block javascript %} 

{% endblock javascript %}

quiz/templates/quiz/game_results.html
{% extends "quiz/base.html" %}

{% block content %}

<h3>Ahoj {{player.nickname}},</h3>
<p>
Získal si {{points}} z {{max_points}} bodov a tvoj čas bol {{game_time}}.
</p>
<div class='row'>
<a class="waves-effect waves-light btn" href="{% url 'quiz:results' %}">Výsledky</a>
<a class="waves-effect waves-light btn" href="{% url 'quiz:create-game' player.id %}">Nová hra</a>
<a class="waves-effect waves-light btn" href="{% url 'quiz:start' %}">Späť na úvod</a>
</div>


{% endblock content %}

quiz/templates/quiz/instructions.html
{% extends "quiz/base.html" %}

{% block content %}

<h3>Ahoj {{player.nickname}},</h3>
<p>
    Tento kvíz pozostáva z 20 otázok. Tvojim cieľom je umiestniť sa do 21.00 čo najvyššie v poradí.
</p>
<p>
    Poradie sa zostavuje primárne podľa počtu správne zodpovedaných otázok. V prípade rovnosti rozhoduje čas, za ktorý kvíz vyplníš.
</p>
<p>
    Odpovedaj na otázku vždy jedným slovom alebo jedným číslom. Odpoveď potvrď buď stlačením tlačidla alebo Entrom. K zodpovedanej otázke sa už nedá vrátiť. Na konci kvízu sa dozvieš koľko odpovedí si mal/a správne. Otázky v kvíze sa menia a teda každý kvíz vyzerá trošku inak. V prípade problémov píšte na kovacs@strom.sk .
</p>
<form action="{% url 'quiz:start-game' pk %}" method='POST'>
    {% csrf_token %}
    <button class="waves-effect waves-light btn" type='submit'>Začni</button>
</form>

{% endblock content %}

quiz/templates/quiz/question.html
{% extends "quiz/base.html" %}

{% block content %}
<div>
    <div class="center-div">
        <h2 style="text-align: center;">{{question_tag}}</h2>
    </div>
    <h4>{{question_text |safe}}</h4>
    <form name="answer_form" action="{% url 'quiz:game' pk %}" method="post">
        {% csrf_token %}
        <label for="answer">Odpoveď: </label>
        <input id="answer" type="text" name="answer" value="" autocomplete='off'>
        <input class="waves-effect waves-light btn" type="submit" value="Odovzdať">
        </form>
</div>

{% endblock content %}

quiz/templates/quiz/results.html
{% extends "quiz/base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6">
            <h2>Poradie</h2>
        </div>
        <div class="col-sm-6">
            <a class="waves-effect waves-light btn" href="{% url 'quiz:start' %}">nová hra</a>
        </div>
    </div>
</div>
<div class="row">
    <table class="striped">
        <thead>
            <tr>
                <th>Poradie</th>
                <th>Účastník</th>
                <th>Body</th>
                <th>Čas</th>
            </tr>
        </thead>
        <tbody>
            {% for res in results %}
            <tr>
                <td>{{forloop.counter}}.</td>
                <td>{{res.player.nickname}}</td>
                <td>{{res.points}}</td>
                <td>{{res.time}} s</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>


{% endblock content %}

quiz/templates/quiz/start.html
{% extends "quiz/base.html" %}
{% load crispy_forms_tags %}
{% load materializecss %}
{% block content %}
<h1>STROMácky kvíz</h1>
Vitajte na stromáckom kvíze, ktorý je súčasťou <a href="https://seminar.strom.sk/onlinestrom/">online sústredenia STROMu 2021</a>.
<br><br>
<a class="waves-effect waves-light btn" href="{% url 'quiz:results' %}">Aktuálne poradie</a>
<br><br>
<hr>
Ak chcete začať hru, zadajte svoj email, pod ktorým ste sa prihlasovali na online sústredká.
<form action="start" method="post">
    {% csrf_token %}
    {{ form |materializecss }}
    <input type="submit" class="waves-effect waves-light btn" value="Štart">
</form>

{% endblock content %}

quiz/templates/quiz/wrong_player.html
{% extends "quiz/base.html" %}

{% block content %}
<p>
    Hráč s emailom {{email}} nie je zaregistrovaný. V prípade, že si vyplnil/a prihlášku na online-sústrednie a prihlásenie ti nefunguje napíš na kovacs@strom.sk
</p>
<a class="waves-effect waves-light btn" href='/quiz/start'>Späť na štart</a>
{% endblock content %}